const totalData = [
  {
    seat: "Seat A",
    // no: 1,
    Price: 250,
    item: "daily",
    image: "https://i.ibb.co/MB8QG59/train.png",
  },
  {
    seat: "Seat B",
    // no: 1,
    Price: 200,
    item: "daily",
    image: "https://i.ibb.co/MB8QG59/train.png",
  },
  {
    seat: "Seat C",
    // no: 1,
    Price: 180,
    item: "daily",
    image: "https://i.ibb.co/MB8QG59/train.png",
  },
  {
    seat: "Seat D",
    // no: 1,
    Price: 150,
    item: "daily",
    image: "https://i.ibb.co/MB8QG59/train.png",
  },
  {
    seat: "Seat A",
    // no: 2,
    Price: 250,
    item: "weekly",
    image: "https://i.ibb.co/MB8QG59/train.png",
  },
  {
    seat: "Seat B",
    // no: 2,
    Price: 200,
    item: "weekly",
    image: "https://i.ibb.co/MB8QG59/train.png",
  },
  {
    seat: "Seat C",
    // no: 2,
    Price: 180,
    item: "weekly",
    image: "https://i.ibb.co/MB8QG59/train.png",
  },
  {
    seat: "Seat D",
    // no: 3,
    Price: 150,
    item: "weekly",
    image: "https://i.ibb.co/MB8QG59/train.png",
  },
  {
    seat: "Seat G",
    // no: 3,
    Price: 200,
    item: "Monthly",
    image: "https://i.ibb.co/MB8QG59/train.png",
  },
  {
    seat: "Seat H",
    // no: 3,
    Price: 180,
    item: "Monthly",
    image: "https://i.ibb.co/MB8QG59/train.png",
  },
  {
    seat: "Seat I",
    // no: 4,
    Price: 150,
    item: "Monthly",
    image: "https://i.ibb.co/MB8QG59/train.png",
  },
  {
    seat: "Seat J",
    // no: 4,
    Price: 100,
    item: "Monthly",
    image: "https://i.ibb.co/MB8QG59/train.png",
  },
  {
    seat: "Seat H",
    // no: 4,
    Price: 180,
    item: "Yearly",
    image: "https://i.ibb.co/MB8QG59/train.png",
  },
  {
    seat: "Seat I",
    // no: 4,
    Price: 150,
    item: "Yearly",
    image: "https://i.ibb.co/MB8QG59/train.png",
  },
  {
    seat: "Seat J",
    // no: 4,
    Price: 100,
    item: "Yearly",
    image: "https://i.ibb.co/MB8QG59/train.png",
  },
];

export default totalData;
